### ISSUE TITLE
Ok, rename for real.

### ISSUE THREAD

**Issue by honestly-nuts** [honestly-nuts/SCore-Utils#26]
I have thought about this a lot and I have come to a division that the project needs to be renamed. i have chosen three names:
PyCoreUtils, PCU (python Core Utils) and PackUtils (packaged utils). Vote for the name you want. If you don't like the names then suggest your own.

**Comment by Kle0s** [comment]
I think you can close it now :)

**Comment by honestly-nuts** [comment]
ohh, I forgot
